deployment:
  host: 0.0.0.0
  port: 8002
  reload: False
  reload-delay: 1

cors:
  allow_origins:
    - "*"
  allow_credentials: False
  allow_methods:
    - GET
    - POST
    - PUT
  allow_headers:
    - "*"

testing:
  local_deploy: True
